### ISSUE TITLE
Grid Component for Automatic Alignment and Stacking

### ISSUE THREAD

**Issue by mlhoutel** [reifocS/maginet#13]
### Description
To improve the organization of elements (such as cards), a grid component should be introduced to automatically align them. The grid would help with consistent spacing and positioning, making it easier to arrange elements on the board. Additionally, stacked elements should have a vertical offset to indicate the depth of the pile, allowing users to see that multiple elements are stacked together.

### Expected Behavior
- Elements should snap to a grid for automatic alignment, ensuring consistent spacing and positioning.
- The grid spacing should be configurable, allowing users to adjust the alignment density.
- When elements are stacked, there should be a small vertical offset for each item in the stack to indicate the depth and make the pile visible.

### Actual Behavior
- Currently, elements are positioned freely without any automatic alignment or grid snapping.

### Environment
- **Operating System:** Windows 10
- **Browser:** Firefox

**Comment by reifocS** [comment]
#17
