### ISSUE TITLE
 Incorrect Drag Behavior When Selecting and Dragging Elements

### ISSUE THREAD

**Issue by mlhoutel** [reifocS/maginet#8]
### Description
When an element is already selected, and the user clicks to start dragging another element before releasing the mouse, both elements are dragged instead of just the second one. This issue occurs because the selection is updated on mouse release rather than on the initial click, leading to incorrect handling of drag events.

### Steps to Reproduce
1. Select an element on the canvas.
2. Click on a different element without releasing the mouse.
3. Start dragging the second element.
4. Observe that both the initially selected element and the new element are dragged together.

### Expected Behavior
- Only the second element (the one clicked on) should be dragged when clicked and dragged, regardless of whether another element was previously selected.

### Actual Behavior
- Both the previously selected element and the newly clicked element are dragged together.

### Additional Context
- The selection is currently being updated on the mouse release (`mouseup`) event rather than the initial mouse click (`mousedown`). The drag operation starts on `mousedown`, causing the selection to be out of sync with the drag operation.

### Environment
- **Operating System:** Windows 10
- **Browser:** Firefox

**Comment by reifocS** [comment]
#16
